journals:
  - openjournals/joss-reviews:
      editor_team_id: 2009411
      eics:
        - arfon
        - danielskatz
        - Kevin-Mattheus-Moerman
        - kthyng
        - kyleniemeyer
      eic_team_name: openjournals/joss-eics
      papers_repo: openjournals/joss-papers
      reviewers: https://bit.ly/joss-reviewers
      reviewers_signup: https://joss.theoj.org/reviewer-signup.html
      site_host: https://joss.theoj.org
      doi_prefix: "10.21105"
      journal_alias: joss
      journal_launch_date: '2016-05-05'
      journal_issn: '2475-9066'
      site_name: Journal of Open Source Software
      donate_url: https://numfocus.org/donate-to-joss
      site_api_key: <%= ENV['JOSS_API_KEY'] %>
      crossref_username: <%= ENV['CROSSREF_USERNAME'] %>
      crossref_password: <%= ENV['CROSSREF_PASSWORD'] %>
      twitter_consumer_key: <%= ENV['JOSS_TWITTER_CONSUMER_KEY'] %>
      twitter_consumer_secret: <%= ENV['JOSS_TWITTER_CONSUMER_SECRET'] %>
      twitter_access_token: <%= ENV['JOSS_TWITTER_ACCESS_TOKEN'] %>
      twitter_access_token_secret: <%= ENV['JOSS_TWITTER_ACCESS_TOKEN_SECRET'] %>

  - openjournals/jose-reviews:
      editor_team_id: 2414911
      eics:
        - labarba
      eic_team_name: openjournals/jose-eics
      papers_repo: openjournals/jose-papers
      reviewers: https://bit.ly/jose-reviewers
      reviewers_signup: http://jose.theoj.org/reviewer-signup.html
      site_host: https://jose.theoj.org
      doi_prefix: "10.21105"
      journal_alias: jose
      journal_launch_date: '2018-03-07'
      journal_issn: '2577-3569'
      site_name: Journal of Open Source Education
      donate_url: https://numfocus.org/donate-to-jose
      site_api_key: <%= ENV['JOSE_API_KEY'] %>
      crossref_username: <%= ENV['CROSSREF_USERNAME'] %>
      crossref_password: <%= ENV['CROSSREF_PASSWORD'] %>

  - JuliaCon/proceedings-review:
      editor_team_id: 3213896
      eics:
        - vchuravy
        - matbesancon
        - arfon
      eic_team_name: JuliaCon/jcon-eics
      papers_repo: JuliaCon/proceedings-papers
      # TODO: Create this spreadsheet or equivalent
      reviewers: http://bit.ly/2V9GSFq
      reviewers_signup: https://forms.gle/yANMe4c9YmuW9MWcA
      site_host: https://proceedings.juliacon.org
      doi_prefix: "10.21105"
      journal_alias: jcon
      journal_launch_date: '2019-04-22'
      journal_issn: '2642-4029'
      current_issue: "1"
      current_volume: "1"
      site_name: JuliaCon Proceedings
      donate_url: https://numfocus.salsalabs.org/donate-to-jcon
      site_api_key: <%= ENV['JCON_API_KEY'] %>
      crossref_username: <%= ENV['CROSSREF_USERNAME'] %>
      crossref_password: <%= ENV['CROSSREF_PASSWORD'] %>

  - openjournals/joss-reviews-testing:
      editor_team_id: 2009411
      eics:
        - arfon
        - xuanxu
      eic_team_name: openjournals/joss-eics-testing
      papers_repo: openjournals/joss-papers-testing
      reviewers: https://bit.ly/joss-reviewers
      reviewers_signup: https://joss.theoj.org/reviewer-signup.html
      site_host: https://test.joss.theoj.org
      doi_prefix: "10.21105"
      journal_alias: joss
      journal_launch_date: '2016-05-05'
      journal_issn: '2475-9066'
      site_name: Journal of Open Source Software
      donate_url: https://numfocus.salsalabs.org/donate-to-joss
      site_api_key: <%= ENV['JOSS_TEST_API_KEY'] %>
      crossref_username: <%= ENV['CROSSREF_TEST_USERNAME'] %>
      crossref_password: <%= ENV['CROSSREF_TEST_PASSWORD'] %>
      twitter_consumer_key:
      twitter_consumer_secret:
      twitter_access_token:
      twitter_access_token_secret:
