journals:
  - openjournals/joss-reviews:
      editor_team_id: 2009411
      eics:
        - arfon
        - labarba
        - danielskatz
        - kyleniemeyer
      papers_repo: openjournals/joss-papers
      reviewers: https://bit.ly/joss-reviewers
      reviewers_signup: http://joss.theoj.org/reviewer-signup.html
      site_host: http://joss.theoj.org
      doi_prefix: "10.21105"
      journal_alias: joss
      journal_launch_date: '2016-05-05'
      journal_issn: '2475-9066'
      site_name: Journal of Open Source Software
      donate_url: https://numfocus.salsalabs.org/donate-to-joss
      site_api_key: <%= ENV['JOSS_API_KEY'] %>
      crossref_username: <%= ENV['CROSSREF_USERNAME'] %>
      crossref_password: <%= ENV['CROSSREF_PASSWORD'] %>

  - openjournals/jose-reviews:
      editor_team_id: 2414911
      eics:
        - labarba
      papers_repo: openjournals/jose-papers
      # TODO: Create this spreadsheet or equivalent
      reviewers: https://bit.ly/jose-reviewers
      reviewers_signup: http://jose.theoj.org/reviewer-signup.html
      site_host: https://jose.theoj.org
      doi_prefix: "10.21105"
      journal_alias: jose
      journal_launch_date: '2018-03-07'
      journal_issn: '2577-3569'
      site_name: Journal of Open Source Education
      donate_url: https://numfocus.salsalabs.org/donate-to-jose
      site_api_key: <%= ENV['JOSE_API_KEY'] %>
      crossref_username: <%= ENV['CROSSREF_USERNAME'] %>
      crossref_password: <%= ENV['CROSSREF_PASSWORD'] %>

  - JuliaCon/proceedings-review:
      editor_team_id: 3213896
      eics:
        - vchuravy
      papers_repo: JuliaCon/proceedings-papers
      # TODO: Create this spreadsheet or equivalent
      reviewers: http://bit.ly/2V9GSFq
      reviewers_signup: https://forms.gle/yANMe4c9YmuW9MWcA
      site_host: https://submissions.juliacon.org
      doi_prefix: "10.21105"
      journal_alias: jcon
      journal_launch_date: '2019-04-22'
      journal_issn: '2642-4029'
      site_name: JuliaCon Proceedings
      donate_url: https://numfocus.salsalabs.org/donate-to-jcon
      site_api_key: <%= ENV['JCON_API_KEY'] %>
      crossref_username: <%= ENV['CROSSREF_USERNAME'] %>
      crossref_password: <%= ENV['CROSSREF_PASSWORD'] %>

  - openjournals/joss-reviews-testing:
      editor_team_id: 2009411
      eics:
        - arfon
      papers_repo: openjournals/joss-papers-testing
      reviewers: https://bit.ly/joss-reviewers
      reviewers_signup: http://staging.joss.theoj.org/reviewer-signup.html
      site_host: http://joss.theoj.org
      doi_prefix: "10.21105"
      journal_alias: joss
      journal_launch_date: '2016-05-05'
      journal_issn: '0000-0000'
      site_name: Journal of Open Source Software Testing
      donate_url: http://example.com
      site_api_key: <%= ENV['JOSS_API_KEY'] %>
      crossref_username: <%= ENV['CROSSREF_USERNAME'] %>
      crossref_password: <%= ENV['CROSSREF_PASSWORD'] %>
