journals:
  - openjournals/joss-reviews-testing:
      editor_team_id: 3408147
      eics:
        - emdupre
      eic_team_name: neurolibre/editors
      papers_repo: neurolibre/neurolibre-papers
      reviewers: https://tinyurl.com/y22xx6ux
      reviewers_signup: ''
      site_host: https://neurolibre.herokuapp.com
      doi_prefix: ""
      journal_alias: NeuroLibre
      journal_launch_date: ''
      site_name: NeuroLibre
      donate_url: ''
      site_api_key: <%= ENV['JOSS_API_KEY'] %>
